#!/usr/bin/env python3
import math, subprocess, sys, tempfile, os

NEC = os.environ.get("NEC2C", "/tmp/nec2c/nec2c")
F = 299.792458

def run(wires, feed, ground=False):
    lines = ["CM", "CE"]
    for tag, (p0, p1, nseg, a) in enumerate(wires, 1):
        lines.append(f"GW {tag} {nseg} {p0[0]:.9f} {p0[1]:.9f} {p0[2]:.9f} {p1[0]:.9f} {p1[1]:.9f} {p1[2]:.9f} {a}")
    lines.append("GE 1" if ground else "GE 0")
    if ground:
        lines.append("GN 1")
    lines.append(f"EX 0 {feed[0]} {feed[1]} 0 1 0")
    lines.append(f"FR 0 1 0 0 {F} 0")
    lines.append("XQ")
    lines.append("EN")
    with tempfile.TemporaryDirectory() as d:
        open(f"{d}/in.nec", "w").write("\n".join(lines) + "\n")
        subprocess.run([NEC, f"-i{d}/in.nec", f"-o{d}/out"], check=True, capture_output=True)
        out = open(f"{d}/out").read()
    row = out.split("ANTENNA INPUT PARAMETERS")[1].split("\n")[3].split()
    return float(row[6]), float(row[7])

def poly(pts, per, a):
    out = []
    for p0, p1 in zip(pts, pts[1:]):
        n = max(1, round(math.dist(p0, p1) * per))
        out.append((p0, p1, n, a))
    return out

cases = []

def case(name, lines, feed_pt, nec_wires, nec_feed, ground=False, radius=0.001):
    z = run(nec_wires, nec_feed, ground)
    cases.append((name, lines, feed_pt, ground, radius, z))

a = 0.001
case("monopole", [[(0, 0, 0), (0, 0, 0.24)]], (0, 0, 0),
     [((0, 0, 0), (0, 0, 0.24), 48, a)], (1, 1), ground=True)

refl, drv, dirl, sR, sD = 0.482, 0.472, 0.442, 0.20, 0.15
case("yagi3",
     [[(-dirl/2, 0, 0), (dirl/2, 0, 0)], [(-drv/2, 0, -sD), (drv/2, 0, -sD)], [(-refl/2, 0, -sD-sR), (refl/2, 0, -sD-sR)]],
     (0, 0, -sD),
     [((-dirl/2, 0, 0), (dirl/2, 0, 0), 45, a), ((-drv/2, 0, -sD), (drv/2, 0, -sD), 47, a), ((-refl/2, 0, -sD-sR), (refl/2, 0, -sD-sR), 49, a)],
     (2, 24))

A, B, Cg, D = 0.3712, 0.0457, 0.0143, 0.0838
drv_pts = [(-A/2, 0, -B), (-A/2, 0, 0), (0, 0, 0), (A/2, 0, 0), (A/2, 0, -B)]
ref_pts = [(-A/2, 0, -(B+Cg)), (-A/2, 0, -(B+Cg+D)), (A/2, 0, -(B+Cg+D)), (A/2, 0, -(B+Cg))]
nd = [((-A/2, 0, -B), (-A/2, 0, 0), 8, a), ((-A/2, 0, 0), (A/2, 0, 0), 71, a), ((A/2, 0, 0), (A/2, 0, -B), 8, a)]
nr = poly(ref_pts, 200, a)
case("moxon", [drv_pts, ref_pts], (0, 0, 0), nd + nr, (2, 36))

rad, rl, dr, g = 0.2375, 0.2375 * 1.05, math.radians(45), 1 / 120
lines = [[(0, 0, g), (0, 0, rad)], [(0, 0, -g), (0, 0, g)]]
nw = [((0, 0, g), (0, 0, rad), 46, a), ((0, 0, -g), (0, 0, g), 3, a)]
for i in range(4):
    th = i * math.pi / 2
    end = (rl * math.cos(dr) * math.cos(th), rl * math.cos(dr) * math.sin(th), -g - rl * math.sin(dr))
    lines.append([(0, 0, -g), end])
    nw.append(((0, 0, -g), end, 50, a))
case("groundplane", lines, (0, 0, 0), nw, (2, 2))

side = 1.02 / 4
h = side / 2
sq = [(0, -h, -h), (0, h, -h), (0, h, h), (0, -h, h), (0, -h, -h)]
loop_lines = [[(0, 0, -h), (0, h, -h), (0, h, h), (0, -h, h), (0, -h, -h), (0, 0, -h)]]
nl = [((0, -h, -h), (0, h, -h), 51, a)] + poly(sq[1:], 200, a)
case("square_loop", loop_lines, (0, 0, -h), nl, (1, 26))

inc = math.radians(60)
arm = 0.245
e = 1 / 120
tipx, tipy = math.sin(inc) * arm, math.cos(inc) * arm
v_lines = [[(-e, 0, 0), (-tipx, tipy, 0)], [(e, 0, 0), (tipx, tipy, 0)], [(-e, 0, 0), (e, 0, 0)]]
nv = [((-e, 0, 0), (-tipx, tipy, 0), 49, a), ((e, 0, 0), (tipx, tipy, 0), 49, a), ((-e, 0, 0), (e, 0, 0), 3, a)]
case("vdipole", v_lines, (0, 0, 0), nv, (3, 2))

def rs(p):
    return "[" + ", ".join(f"{float(v) * 1000:.6f}" for v in p) + "]"

print("// generated by scripts/nec_vectors.py from nec2c, lambda = 1000 mm")
print("pub struct Vector { pub name: &'static str, pub lines: &'static [&'static [[f64; 3]]], pub feed: [f64; 3], pub ground: bool, pub radius: f64, pub z: (f64, f64) }")
print("pub const VECTORS: &[Vector] = &[")
for name, lines, feed, ground, radius, z in cases:
    ls = ", ".join("&[" + ", ".join(rs(p) for p in l) + "]" for l in lines)
    print(f"    Vector {{ name: \"{name}\", lines: &[{ls}], feed: {rs(feed)}, ground: {str(ground).lower()}, radius: {radius * 1000}, z: ({z[0]}, {z[1]}) }},")
print("];")
